config/routes.rb
Subtract::Application.routes.draw do

  
  resources :blogs do
    resources :posts
  end
  
  resources :posts
  
  get "/auth/:provider/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", :as => :signout
  get "/status" => "sessions#status"
  
  root :to => 'blogs#index'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  validates_presence_of :user_id, :name
  has_many :posts
  belongs_to :user
  
  def latitude
    posts.select('AVG(latitude) as latitude').group('posts.id').first.latitude
  end
  
  def longitude
    posts.select('AVG(longitude) as longitude').group('posts.id').first.longitude
  end
  
end

app/models/post.rb
class Post < ActiveRecord::Base
  # attr_accessible :title, :place, :content, :latitude, :longitude
  validates_presence_of :content, :place, :latitude, :longitude
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :blogs
  
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["nickname"]
    end
  end
  
  def invited?
    name == 'bnolan'
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  private

  def user_required
    if current_user.nil?
      render :text => "You must log in to access this resource"
    end
  end
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_filter :user_required, :only => [:new, :create, :edit, :update]

  def create
    @blog = current_user.blogs.build(blog_params)

    if @blog.save
      redirect_to @blog
    else
      render :action => :create
    end
  end
  
  def show
    @blog = Blog.find(params[:id])
  end
  
  private
  
  def blog_params
    params.require(:blog).permit(:name)
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :user_required, :only => [:new, :create, :edit, :update, :destroy]
  
  def index
    @posts = Post.order('created_at desc').all
  end
  
  def show
    @post = Post.find(params[:id])

    @blog = if params[:blog_id]
      Blog.find(params[:blog_id])
    else
      @post.blog
    end
  end
    
  def create
    post = current_user.posts.build(post_params)
    
    if params[:post][:blog_id].match /Create/
      blog = current_user.blogs.build(blog_params)

      if blog.save
        post.blog_id = blog.id
      else
        raise Exception, "Boohoo"
      end
    end

    if post.save
      redirect_to post
    else
      raise Exception, "Boohoo"
    end
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end
  
  def update
    post = current_user.posts.find(params[:id])
    post.attributes = post_params
    
    if params[:post][:blog_id].match /Create/
      blog = current_user.blogs.build(blog_params)

      if blog.save
        post.blog_id = blog.id
      else
        raise Exception, "Boohoo"
      end
    end
    
    if post.save
      flash[:message] = "Changes to your post were saved"
      redirect_to post
    else
      raise Exception, "Boohoohoo"
    end
  end
  
  def destroy
    post = Post.find(params[:id])
    post.destroy
    render :json => { :success => true }
  end

  private
  
  def post_params
    params.require(:post).permit(:place, :content, :address, :latitude, :longitude, :blog_id)
  end
  
  def blog_params
    params.require(:blog).permit(:name)
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end

  def status
    render :json => current_user
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/blogs/create.js.erb
<% @blog.errors.each do |k,v| %>
  alert(<%= ["Error:\n\n", k,v].join(" ").to_json.html_safe %>);
<% end %>

app/views/blogs/index.html.erb
<header id="header">
  <% if current_user %>
    <%= link_to "Log out", signout_path, :class => 'button left' %>
  <% else %>
    <%= link_to "Log in", "/auth/twitter", :class => 'button left' %>
  <% end %>

  <h1>Subtract</h1>

  <% if current_user && current_user.invited? %>
    <%= link_to "+ Post", new_post_path, :class => 'button right' %>
  <% end %>
</header>

<section>

  <% Blog.all.each do |blog| %>

    <a class="blog" href="<%= blog_path(blog) %>">
      <h3><%= blog.name %></h3>
      <p class="meta">Created by <%= blog.user.name %>, <%= time_ago_in_words blog.created_at %> ago. Has <%= pluralize blog.posts.count, 'post' %>.</p>
      <span class="chevron">&raquo;</span>
    </a>

  <% end %>
  
</section>

app/views/blogs/new.html.erb
<header id="header">
  <h1>New Post</h1>
</header>

<%= form_for(Blog.new, remote: true) do |f| %>
  <%= f.text_field :name, :placeholder => "Name this blog", :id => "new-blog", :autofocus => true, "data-behavior" => "submit_on_enter" %>
  <%= submit_tag "Create" %>
<% end %>

app/views/blogs/show.html.erb
<header id="header">
  <%= link_to "< Back", root_path, :class => 'button left' %>
  
  <h1><%= @blog.name %></h1>

  <%= link_to "+ Post", new_blog_post_path(@blog), :class => 'button right' %>
</header>

<section>
  <div class="map overview-map">
    <%= image_tag "http://api.tiles.mapbox.com/v3/examples.map-vyofok3q/pin-m-star+ff6633(#{@blog.longitude},#{@blog.latitude})/#{@blog.longitude},#{@blog.latitude},1/480x160.png", :class => 'static-map' %>
    <%# image_tag "map-overlay.png", :class => 'map-overlay' %>
    <div class="description">
      Created by @<%= @blog.user.name %> in <%= @blog.created_at.strftime("%B %Y") %>.
    </div>
  </div>

  <% @blog.posts.reverse.each do |post| %>
    <div class="post">
      <h2>
        <%= link_to post.place, [@blog, post] %>
        <span class="chevron">&raquo;</span>
      </h2>
      <address><%= link_to (post.address || "34 Some Street, Blah blah"), [@blog, post] %></address>
      <div class="map">
        <%= image_tag "http://api.tiles.mapbox.com/v3/examples.map-vyofok3q/pin-m-star+ff6633(#{post.longitude},#{post.latitude})/#{post.longitude},#{post.latitude},15/480x160.png", :class => 'static-map', :width => 480, :height => 160 %>
        <%# image_tag "map-overlay.png", :class => 'map-overlay' %>
      </div>
      <div class="content">
        <%= simple_format post.content %>
      </div>
      <small class="meta">
        Posted <%= time_ago_in_words post.created_at %> ago.
      </small>
      <%# image_tag "http://api.tiles.mapbox.com/v3/examples.map-vyofok3q/pin-m-star+ff6633(#{post.longitude},#{post.latitude})/#{post.longitude},#{post.latitude},15/320x240.png" %>
    </div>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Subtract</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <script src="http://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places"></script>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<header id="header">
  <%= link_to "< Back", root_path, :class => 'button left' %>
  
  <h1>Edit Post</h1>

  <%= link_to_function "Save", "$('form').submit()", :class => 'button right' %>
</header>

<section>
  <%= form_for @post do |f| %>
    <ul class="tabs" style="display: none">
      <li class="active">Search for<br /><b>Establishment</b></li>
      <li>Search for<br /><b>Locality</b></li>
      <li>Use current<br /><b>Location</b></li>
    </ul>
    
    <div class="f f-place">
      <%= f.text_field :place, :placeholder => "Name of Establishment" %>
      <button>Change</button>
      <address><%= f.object.address %></address>
    </div>

    <div class="f f-blog">
      <%= f.select :blog_id, ["Select a Blog"] + [''] + Blog.all.collect { |blog| [blog.name, blog.id] } + [''] + ["Create a new Blog"] %>
      <%= fields_for Blog.new do |ff| %>
        <%= ff.text_field :name, :placeholder => "Name of Blog" %>
      <% end %>
    </div>

    <%= f.hidden_field :address %>
    <%= f.hidden_field :latitude %>
    <%= f.hidden_field :longitude %>
  
    <div class="f">
      <%= f.text_area :content, :placeholder => "Post Content" %>
    </div>
  <% end %>
</section>

<div style="width: 100px; height: 100px" id="map"></div>

<script>
  $(function(){
    new PostDialog
  });
</script>

app/views/posts/index.html.erb
<header id="header">
  <% if current_user %>
    <%= link_to "Log out", signout_path, :class => 'button left' %>
  <% else %>
    <%= link_to "Log in", "/auth/twitter", :class => 'button left' %>
  <% end %>

  <h1>Subtract</h1>

  <% if current_user && current_user.invited? %>
    <%= link_to "+ Post", new_post_path, :class => 'button right' %>
  <% end %>
</header>

<section>

  <p class="default-text">
    There is nothing here yet.
  </p>

  <% if @posts.empty? %>
    <p>
      You have no posts in this blog yet.
    </p>
  <% end %>

  <% [].each do |post| %>
    <div class="post">
      <h3><%= link_to post.place, post %></h3>
      <h4><%= post.title %></h4>
      <div class="content">
        <%= simple_format post.content %>
      </div>
      <small class="meta">
        Posted <%= time_ago_in_words post.created_at %> ago.
      </small>
      <%= image_tag "http://api.tiles.mapbox.com/v3/examples.map-vyofok3q/pin-m-star+ff6633(#{post.longitude},#{post.latitude})/#{post.longitude},#{post.latitude},15/320x240.png" %>
    </div>
  <% end %>
</section>

app/views/posts/new.html.erb
<header id="header">
  <%= link_to "< Back", root_path, :class => 'button left' %>
  
  <h1>New Post</h1>

  <%= link_to_function "Post", "$('form').submit()", :class => 'button right' %>
</header>

<section>
  <%= form_for Post.new, :remote => true do |f| %>
    <ul class="tabs">
      <li class="active">Search for<br /><b>Establishment</b></li>
      <li>Search for<br /><b>Locality</b></li>
      <li>Use current<br /><b>Location</b></li>
    </ul>
    
    <div class="f f-place">
      <%= f.text_field :place, :placeholder => "Name of Establishment" %>
      <button>Change</button>
      <address>1278 cuba street, blah blah blah</address>
    </div>

    <div class="f f-blog">
      <%= f.select :blog_id, ["Select a Blog"] + [''] + Blog.all.collect { |blog| [blog.name, blog.id] } + [''] + ["Create a new Blog"] %>
      <%= fields_for Blog.new do |ff| %>
        <%= ff.text_field :name, :placeholder => "Name of Blog" %>
      <% end %>
    </div>

    <%= f.hidden_field :address %>
    <%= f.hidden_field :latitude %>
    <%= f.hidden_field :longitude %>
  
    <%# image_tag "https://maps.gstatic.com/mapfiles/api-3/images/powered-by-google-on-white2.png" %>
  
    <!--div class="f">
      <%= f.text_field :title, :placeholder => "Title" %>
    </div-->
  
    <div class="f">
      <%= f.text_area :content, :placeholder => "Post Content" %>
    </div>
  <% end %>
</section>

<div style="width: 100px; height: 100px" id="map"></div>

<script>
  $(function(){
    new PostDialog
  });
</script>

app/views/posts/show.html.erb
<header id="header">
  <%= link_to "< Back", blog_path(@blog), :class => 'button left' %>
  
  <h1><%= truncate(@post.place) %></h1>

  <%= link_to "Edit", edit_blog_post_path(@blog, @post), :class => 'button right' %>
</header>

<section>
  <div class="post">
    <h2>
      <%= link_to @post.place, [@blog, @post] %>
    </h2>
    <address><%= @post.address || "34 Some Street, Blah blah" %></address>
    <div class="map">
      <%= image_tag "http://api.tiles.mapbox.com/v3/examples.map-vyofok3q/pin-m-star+ff6633(#{@post.longitude},#{@post.latitude})/#{@post.longitude},#{@post.latitude},14/480x160.png", :class => 'static-map' %>
      <%# image_tag "map-overlay.png", :class => 'map-overlay' %>
    </div>
    <div class="content">
      <%= simple_format @post.content %>
    </div>
    <small class="meta">
      Posted <%= time_ago_in_words @post.created_at %> ago.
    </small>
  </div>
</section>